# Basic Information 
title: Junteng Liu
description: "Junteng Liu's Homepage"
url: "https://ekasischi.github.io"
baseurl: "/LJT-Homepage"
repository: "ekasischi/LJT-Homepage"

# The description that appears at the top of the sidebar. 
owner:
  name: "Junteng Liu"
  avatar: "/assets/images/bio-photo.jpg"
  description: "I am a first-year PhD candidate at HKUST NLP Group."
  email: "jliugi@connect.ust.hk"
  github: "Vicent0205"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  twitter: "junteng88716710"

# Reading Files
include:
  - .nojekyll
  - _pages

# Excluding any files or directories from the website
exclude:
  - _posts
  - _talks
  - _teaching
  - _portfolio
  - _drafts
  - vendor
  - __tasks
  - CNAME
  - empty
  - docs
  - files
  - README.md
  - tmp
  - talkmap.ipynb
  - talkmap_out.ipynb
  - talkmap.py
  - talkmap
  - scripts
  - markdown_generator
  - package.json
  - Dockerfile
  - docker-compose.yaml
  - .github
  - .devcontainer
  - AGENTS.md

# Site Author
author:
  name: "Junteng Liu"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "First-year PhD candidate at HKUST NLP Group."
  location: "Hong Kong"
  email: "jliugi@connect.ust.hk"
  github: "Vicent0205"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  twitter: "junteng88716710"

# Reading Files
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"
